### ISSUE TITLE
[CRSH] Program version v5.0.0 crashes on launch with System.ArgumentException, previous version worked fine.

### ISSUE THREAD

**Issue by lds1998** [timschneeb/GalaxyBudsClient#518] opened 2024-06-23 08:34 UTC
**Shortly describe what were you doing before crash**
Listening to music on Spotify and trying to launch the program both regular and with admin permissions.

**Include event files here**
[EventLogs.zip](https://github.com/user-attachments/files/15943831/EventLogs.zip)
<details><summary>Details</summary>
<p>

Application: Galaxy Buds Client.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: O parâmetro está incorreto.

The provided device ID is not a valid BluetoothDevice object.
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.<.ctor>b__35_4(DeviceWatcher watcher, DeviceInformation deviceInfo)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

</p>
</details> 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 64bit (Build: 23H2 22631.3737)
 - Application version: v5.0.0
 - Galaxy Buds FE

**Additional context**
Reinstalled and clean the cache of the installed version & also tried the portable version and clean the cache, but problem persists.

Official App works without problem, official app was removed to see if was causing some incompatibility, same effect.
**Previous version v4.6.0, worked without issues.**

**Comment by BoyceXX** [comment] 2024-06-25 01:50
same here, same Buds FE, when bluetooth on PC is off, this app will survive one two seconds longer, i was able to interact with UI, but after that it still quite by itself.
When bluetooth is on, it exits immediately before the UI is fully loaded.

**Comment by timschneeb** [comment] 2024-06-26 21:30
Duplicate of #513

**Closed by timschneeb** 2024-06-26 21:30 UTC
Labels: crash
