### ISSUE TITLE
[CRSH] App crashes on launch with System.ArgumentException

### ISSUE THREAD

**Issue by 0xD3N1Z** [timschneeb/GalaxyBudsClient#517] opened 2024-06-22 17:30 UTC
**Shortly describe what were you doing before crash**
Simply launching the program with double click

**Include event files here**
```
Application: GalaxyBudsClient_Windows_64bit_Portable.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Parametre hatalı.

The provided device ID is not a valid BluetoothDevice object.
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.<.ctor>b__35_4(DeviceWatcher watcher, DeviceInformation deviceInfo)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
[event_logs.zip](https://github.com/user-attachments/files/15937549/event_logs.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (Build 22631.3737) 64-Bit
 - Application version: v5.0.0

**Additional context**
Reinstalled & also tried the portable version. Tried clearing the cache (didn't fix it), also first time installing it on this pc setup.

Also tried removing and adding the Buds in bluetooth settings (Buds2)

The official Galaxy Buds app is also installed and running, normally it wouldn't interfere with older versions but the recent (~1 year ago) quick controls feature they added might be causing a problem.

Everything is up-to-date.

Might be related to https://github.com/timschneeb/GalaxyBudsClient/issues/125

**Comment by timschneeb** [comment] 2024-06-26 21:29
Duplicate of #513

**Closed by timschneeb** 2024-06-26 21:29 UTC
Labels: crash
